#!/usr/bin/env node
// IWP Work Tracker v2 — simple single-function backend
// Usage: node setup-v2.mjs

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';

const ROOT = process.cwd();
const files = {};
const file = (p, c) => { files[p] = c; };
const S = (...lines) => lines.join('\n');

// ═════════════════════════════════════════════════════════════
// ROOT CONFIG
// ═════════════════════════════════════════════════════════════

file('.gitignore', S(
  'node_modules', 'dist', '.env', '.env.local', '.DS_Store', '*.log', '.vercel', ''
));

file('.env.example', S(
  '# Supabase (get from https://supabase.com → your project → Settings → API)',
  'SUPABASE_URL=https://yzeyzoitkeiobqunklhw.supabase.co',
  'SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6ZXl6b2l0a2Vpb2JxdW5rbGh3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc5MDA1NTM4MCwiZXhwIjoyMTA1NjMxMzgwfQ.ILBx1Df-iwwJEEYIxHpT9o2IAVIRB0hgwR70cCEz-JE',
  '',
  '# App password (you choose this — used to log in)',
  'APP_PASSWORD=change-me',
  ''
));

file('package.json', JSON.stringify({
  name: 'iwp-work-tracker',
  private: true,
  version: '2.0.0',
  type: 'module',
  scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
  dependencies: {
    '@supabase/supabase-js': '^2.45.0',
    'html2canvas': '^1.4.1',
    'jspdf': '^2.5.1',
    'react': '^18.3.1',
    'react-dom': '^18.3.1',
    'react-markdown': '^9.0.1',
    'react-router-dom': '^6.26.0',
    'recharts': '^2.12.7',
    'xlsx': '^0.18.5',
  },
  devDependencies: {
    '@vitejs/plugin-react': '^4.3.1',
    'autoprefixer': '^10.4.19',
    'postcss': '^8.4.40',
    'tailwindcss': '^3.4.7',
    'vite': '^5.3.5',
  },
}, null, 2) + '\n');

file('vite.config.js', S(
  "import { defineConfig } from 'vite';",
  "import react from '@vitejs/plugin-react';",
  '',
  'export default defineConfig({',
  '  plugins: [react()],',
  '  server: { port: 5173 },',
  '});',
  ''
));

file('tailwind.config.js', S(
  '/** @type {import("tailwindcss").Config} */',
  'export default {',
  "  content: ['./index.html', './src/**/*.{js,jsx}'],",
  "  darkMode: 'class',",
  '  theme: {',
  '    extend: {',
  '      colors: {',
  "        bg: 'rgb(var(--bg) / <alpha-value>)',",
  "        panel: 'rgb(var(--panel) / <alpha-value>)',",
  "        border: 'rgb(var(--border) / <alpha-value>)',",
  "        text: 'rgb(var(--text) / <alpha-value>)',",
  "        muted: 'rgb(var(--muted) / <alpha-value>)',",
  "        accent: 'rgb(var(--accent) / <alpha-value>)',",
  '      },',
  '    },',
  '  },',
  '  plugins: [],',
  '};',
  ''
));

file('postcss.config.js', S(
  'export default {',
  '  plugins: { tailwindcss: {}, autoprefixer: {} },',
  '};',
  ''
));

file('index.html', S(
  '<!doctype html>',
  '<html lang="en">',
  '  <head>',
  '    <meta charset="UTF-8" />',
  "    <link rel=\"icon\" href=\"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>📓</text></svg>\" />",
  '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  '    <title>IWP Work Tracker</title>',
  '  </head>',
  '  <body>',
  '    <div id="root"></div>',
  '    <script type="module" src="/src/main.jsx"></script>',
  '  </body>',
  '</html>',
  ''
));

// NO vercel.json — Vercel auto-detects /api/index.js and serves everything else as static
// This avoids all the rewrite-related problems we had.

// ═════════════════════════════════════════════════════════════
// SUPABASE SCHEMA
// ═════════════════════════════════════════════════════════════

file('supabase/schema.sql', S(
  '-- IWP Work Tracker v2 schema — run this once in Supabase SQL Editor',
  '',
  'create table if not exists entries (',
  '  id            bigserial primary key,',
  '  date          date not null,',
  '  title         text not null,',
  "  description   text default '',",
  "  category      text default 'Other',",
  "  project       text default '',",
  '  hours         numeric(6,2) default 0,',
  "  status        text default 'Completed',",
  '  is_highlight  boolean default false,',
  "  links         jsonb default '[]'::jsonb,",
  '  created_at    timestamptz default now(),',
  '  updated_at    timestamptz default now()',
  ');',
  'create index if not exists idx_entries_date      on entries(date);',
  'create index if not exists idx_entries_project   on entries(project);',
  'create index if not exists idx_entries_category  on entries(category);',
  'create index if not exists idx_entries_highlight on entries(is_highlight);',
  '',
  'create table if not exists categories (',
  '  id     bigserial primary key,',
  '  name   text unique not null,',
  "  color  text default '#64748b',",
  '  sort   int default 0',
  ');',
  '',
  'create table if not exists drafts (',
  '  id         int primary key default 1 check (id = 1),',
  '  payload    jsonb not null,',
  '  updated_at timestamptz default now()',
  ');',
  '',
  'insert into categories (name, color, sort) values',
  "  ('Development','#3b82f6',0),('Design','#a855f7',1),('Meetings','#f59e0b',2),",
  "  ('Documentation','#10b981',3),('Research','#06b6d4',4),('Admin','#64748b',5),",
  "  ('Client Work','#ec4899',6),('Learning','#8b5cf6',7),('Other','#94a3b8',8)",
  'on conflict (name) do nothing;',
  '',
  'create or replace function set_updated_at() returns trigger as $$',
  'begin new.updated_at = now(); return new; end;',
  '$$ language plpgsql;',
  '',
  'drop trigger if exists trg_entries_updated on entries;',
  'create trigger trg_entries_updated',
  '  before update on entries',
  '  for each row execute function set_updated_at();',
  '',
  'alter table entries    enable row level security;',
  'alter table categories enable row level security;',
  'alter table drafts     enable row level security;',
  ''
));

// ═════════════════════════════════════════════════════════════
// SINGLE BACKEND FILE — /api/index.js
// Vercel automatically routes /api/* to this file.
// ═════════════════════════════════════════════════════════════

file('api/index.js', S(
  "import { createClient } from '@supabase/supabase-js';",
  '',
  '// ─── Supabase client (initialized once per cold start) ───',
  'let supabase = null;',
  'function getSupabase() {',
  '  if (supabase) return supabase;',
  '  const url = process.env.SUPABASE_URL;',
  '  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;',
  '  if (!url || !key) throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");',
  '  supabase = createClient(url, key, { auth: { persistSession: false } });',
  '  return supabase;',
  '}',
  '',
  '// ─── Helpers ───',
  'const rowToEntry = (r) => r ? {',
  '  id: r.id, date: r.date, title: r.title, description: r.description || "",',
  '  category: r.category || "Other", project: r.project || "",',
  '  hours: Number(r.hours) || 0, status: r.status || "Completed",',
  '  isHighlight: !!r.is_highlight, links: Array.isArray(r.links) ? r.links : [],',
  '  createdAt: r.created_at, updatedAt: r.updated_at,',
  '} : null;',
  '',
  'const bodyToRow = (b = {}) => ({',
  '  date: b.date || new Date().toISOString().slice(0, 10),',
  '  title: String(b.title || "").trim() || "Untitled",',
  '  description: String(b.description || ""),',
  '  category: b.category || "Other",',
  '  project: String(b.project || "").trim(),',
  '  hours: Number(b.hours) || 0,',
  '  status: b.status || "Completed",',
  '  is_highlight: !!b.isHighlight,',
  '  links: Array.isArray(b.links) ? b.links.filter(Boolean) : [],',
  '});',
  '',
  '// ─── Auth ───',
  'function checkAuth(req, res) {',
  '  const expected = process.env.APP_PASSWORD;',
  '  if (!expected) return true; // no password set → open',
  '  const provided = req.headers["x-app-password"] || "";',
  '  if (provided !== expected) {',
  '    res.status(401).json({ error: "Unauthorized" });',
  '    return false;',
  '  }',
  '  return true;',
  '}',
  '',
  '// ═══════════════════════════════════════════════════════════',
  '// MAIN HANDLER — every /api/* request lands here',
  '// ═══════════════════════════════════════════════════════════',
  '',
  'export default async function handler(req, res) {',
  '  try {',
  '    // Handle CORS preflight',
  '    if (req.method === "OPTIONS") return res.status(200).end();',
  '',
  '    // Parse the action from query string',
  '    const action = req.query.action || "";',
  '',
  '    // Health check — no auth required',
  '    if (action === "ping") {',
  '      return res.json({ ok: true, time: new Date().toISOString() });',
  '    }',
  '',
  '    // Debug — no auth required, shows env var presence',
  '    if (action === "debug") {',
  '      return res.json({',
  '        hasUrl: !!process.env.SUPABASE_URL,',
  '        hasKey: !!process.env.SUPABASE_SERVICE_ROLE_KEY,',
  '        hasPassword: !!process.env.APP_PASSWORD,',
  '        urlHost: (process.env.SUPABASE_URL || "").replace(/^https?:\\/\\//, ""),',
  '      });',
  '    }',
  '',
  '    // Everything else requires auth',
  '    if (!checkAuth(req, res)) return;',
  '',
  '    const sb = getSupabase();',
  '',
  '    // ── ENTRIES ──────────────────────────────────────────',
  '    if (action === "entries.list") {',
  '      let q = sb.from("entries").select("*")',
  '        .order("date", { ascending: false })',
  '        .order("id", { ascending: false });',
  '      const f = req.query;',
  '      if (f.from)     q = q.gte("date", f.from);',
  '      if (f.to)       q = q.lte("date", f.to);',
  '      if (f.category) q = q.eq("category", f.category);',
  '      if (f.project)  q = q.eq("project", f.project);',
  '      if (f.status)   q = q.eq("status", f.status);',
  '      if (f.highlight === "true") q = q.eq("is_highlight", true);',
  '      if (f.q) q = q.or(`title.ilike.%${f.q}%,description.ilike.%${f.q}%,project.ilike.%${f.q}%`);',
  '      if (f.limit) q = q.range(Number(f.offset) || 0, (Number(f.offset) || 0) + Number(f.limit) - 1);',
  '      const { data, error } = await q;',
  '      if (error) return res.status(500).json({ error: error.message });',
  '      return res.json(data.map(rowToEntry));',
  '    }',
  '',
  '    if (action === "entries.create") {',
  '      const row = bodyToRow(req.body);',
  '      const { data, error } = await sb.from("entries").insert(row).select().single();',
  '      if (error) return res.status(500).json({ error: error.message });',
  '      return res.status(201).json(rowToEntry(data));',
  '    }',
  '',
  '    if (action === "entries.get") {',
  '      const { data, error } = await sb.from("entries").select("*").eq("id", req.query.id).single();',
  '      if (error) return res.status(404).json({ error: "Not found" });',
  '      return res.json(rowToEntry(data));',
  '    }',
  '',
  '    if (action === "entries.update") {',
  '      const row = bodyToRow(req.body);',
  '      const { data, error } = await sb.from("entries").update(row).eq("id", req.query.id).select().single();',
  '      if (error) return res.status(500).json({ error: error.message });',
  '      return res.json(rowToEntry(data));',
  '    }',
  '',
  '    if (action === "entries.delete") {',
  '      const { error } = await sb.from("entries").delete().eq("id", req.query.id);',
  '      if (error) return res.status(500).json({ error: error.message });',
  '      return res.json({ ok: true });',
  '    }',
  '',
  '    if (action === "entries.star") {',
  '      const { data: cur, error: e1 } = await sb.from("entries").select("is_highlight").eq("id", req.query.id).single();',
  '      if (e1) return res.status(404).json({ error: "Not found" });',
  '      const next = !cur.is_highlight;',
  '      const { error } = await sb.from("entries").update({ is_highlight: next }).eq("id", req.query.id);',
  '      if (error) return res.status(500).json({ error: error.message });',
  '      return res.json({ isHighlight: next });',
  '    }',
  '',
  '    if (action === "entries.duplicate") {',
  '      const { data: src, error: e1 } = await sb.from("entries").select("*").eq("id", req.query.id).single();',
  '      if (e1) return res.status(404).json({ error: "Not found" });',
  '      const { id: _d, created_at, updated_at, ...rest } = src;',
  '      const next = { ...rest, date: (req.body && req.body.date) || new Date().toISOString().slice(0, 10), is_highlight: false };',
  '      const { data, error } = await sb.from("entries").insert(next).select().single();',
  '      if (error) return res.status(500).json({ error: error.message });',
  '      return res.status(201).json(rowToEntry(data));',
  '    }',
  '',
  '    // ── DRAFT ────────────────────────────────────────────',
  '    if (action === "draft.get") {',
  '      const { data } = await sb.from("drafts").select("*").eq("id", 1).maybeSingle();',
  '      return res.json(data ? { payload: data.payload, updatedAt: data.updated_at } : { payload: null });',
  '    }',
  '    if (action === "draft.save") {',
  '      const { error } = await sb.from("drafts").upsert({ id: 1, payload: req.body || {}, updated_at: new Date().toISOString() });',
  '      if (error) return res.status(500).json({ error: error.message });',
  '      return res.json({ ok: true });',
  '    }',
  '    if (action === "draft.clear") {',
  '      await sb.from("drafts").delete().eq("id", 1);',
  '      return res.json({ ok: true });',
  '    }',
  '',
  '    // ── CATEGORIES ───────────────────────────────────────',
  '    if (action === "categories.list") {',
  '      const { data, error } = await sb.from("categories").select("*").order("sort").order("name");',
  '      if (error) return res.status(500).json({ error: error.message });',
  '      return res.json(data);',
  '    }',
  '    if (action === "categories.create") {',
  '      const { name, color = "#64748b" } = req.body || {};',
  '      if (!name) return res.status(400).json({ error: "name required" });',
  '      const { data: maxRow } = await sb.from("categories").select("sort").order("sort", { ascending: false }).limit(1).maybeSingle();',
  '      const sort = ((maxRow && maxRow.sort) || 0) + 1;',
  '      const { data, error } = await sb.from("categories").insert({ name: name.trim(), color, sort }).select().single();',
  '      if (error) return res.status(400).json({ error: error.message });',
  '      return res.status(201).json(data);',
  '    }',
  '    if (action === "categories.update") {',
  '      const patch = {};',
  '      if (req.body && req.body.name) patch.name = req.body.name;',
  '      if (req.body && req.body.color) patch.color = req.body.color;',
  '      const { data, error } = await sb.from("categories").update(patch).eq("id", req.query.id).select().single();',
  '      if (error) return res.status(500).json({ error: error.message });',
  '      return res.json(data);',
  '    }',
  '    if (action === "categories.delete") {',
  '      const { error } = await sb.from("categories").delete().eq("id", req.query.id);',
  '      if (error) return res.status(500).json({ error: error.message });',
  '      return res.json({ ok: true });',
  '    }',
  '',
  '    // ── PROJECTS ─────────────────────────────────────────',
  '    if (action === "projects.list") {',
  '      const { data, error } = await sb.from("entries").select("project, hours, date, is_highlight").neq("project", "");',
  '      if (error) return res.status(500).json({ error: error.message });',
  '      const map = new Map();',
  '      for (const r of data) {',
  '        if (!map.has(r.project)) map.set(r.project, { project: r.project, entries: 0, hours: 0, first_date: r.date, last_date: r.date, highlights: 0 });',
  '        const a = map.get(r.project);',
  '        a.entries++; a.hours += Number(r.hours) || 0;',
  '        if (r.date < a.first_date) a.first_date = r.date;',
  '        if (r.date > a.last_date) a.last_date = r.date;',
  '        if (r.is_highlight) a.highlights++;',
  '      }',
  '      return res.json([...map.values()].sort((a, b) => b.last_date.localeCompare(a.last_date)));',
  '    }',
  '    if (action === "projects.names") {',
  '      const { data, error } = await sb.from("entries").select("project").neq("project", "");',
  '      if (error) return res.status(500).json({ error: error.message });',
  '      const counts = new Map();',
  '      for (const r of data) counts.set(r.project, (counts.get(r.project) || 0) + 1);',
  '      return res.json([...counts.entries()].map(([name, uses]) => ({ name, uses })).sort((a, b) => b.uses - a.uses).slice(0, 200));',
  '    }',
  '',
  '    // ── STATS ────────────────────────────────────────────',
  '    if (action === "stats.recent") {',
  '      const limit = Number(req.query.limit) || 5;',
  '      const { data, error } = await sb.from("entries").select("*")',
  '        .order("date", { ascending: false }).order("id", { ascending: false }).limit(limit);',
  '      if (error) return res.status(500).json({ error: error.message });',
  '      return res.json(data.map(rowToEntry));',
  '    }',
  '',
  '    if (action === "stats.summary") {',
  '      const year = Number(req.query.year) || new Date().getFullYear();',
  '      const yearStart = year + "-01-01", yearEnd = year + "-12-31";',
  '      const now = new Date();',
  '      const iso = (d) => d.toISOString().slice(0, 10);',
  '      const sow = (d) => { const x = new Date(d); const k = (x.getDay() + 6) % 7; x.setDate(x.getDate() - k); x.setHours(0, 0, 0, 0); return x; };',
  '      const wkStart = iso(sow(now)); const wkEndD = sow(now); wkEndD.setDate(wkEndD.getDate() + 6); const wkEnd = iso(wkEndD);',
  '      const moStart = iso(new Date(now.getFullYear(), now.getMonth(), 1));',
  '      const moEnd = iso(new Date(now.getFullYear(), now.getMonth() + 1, 0));',
  '      const today = iso(now);',
  '',
  '      const { data: yearRows, error } = await sb.from("entries").select("*").gte("date", yearStart).lte("date", yearEnd);',
  '      if (error) return res.status(500).json({ error: error.message });',
  '',
  '      const inR = (a, b) => yearRows.filter((r) => r.date >= a && r.date <= b);',
  '      const sumH = (rows) => rows.reduce((s, r) => s + (Number(r.hours) || 0), 0);',
  '      const catMap = new Map(), monthMap = new Map(), statusMap = new Map();',
  '      for (const r of yearRows) {',
  '        catMap.set(r.category, catMap.get(r.category) || { name: r.category, count: 0, hours: 0 });',
  '        const c = catMap.get(r.category); c.count++; c.hours += Number(r.hours) || 0;',
  '        const m = r.date.slice(0, 7);',
  '        monthMap.set(m, monthMap.get(m) || { month: m, count: 0, hours: 0 });',
  '        const mo = monthMap.get(m); mo.count++; mo.hours += Number(r.hours) || 0;',
  '        statusMap.set(r.status, (statusMap.get(r.status) || 0) + 1);',
  '      }',
  '',
  '      const { data: dateRows } = await sb.from("entries").select("date").order("date", { ascending: false }).limit(400);',
  '      const dates = new Set((dateRows || []).map((r) => r.date));',
  '      let streak = 0; const cur = new Date(today);',
  '      if (!dates.has(today)) {',
  '        cur.setDate(cur.getDate() - 1);',
  '        if (dates.has(iso(cur))) { while (dates.has(iso(cur))) { streak++; cur.setDate(cur.getDate() - 1); } }',
  '      } else { while (dates.has(iso(cur))) { streak++; cur.setDate(cur.getDate() - 1); } }',
  '',
  '      return res.json({',
  '        year,',
  '        yearEntries: yearRows.length, yearHours: sumH(yearRows),',
  '        monthEntries: inR(moStart, moEnd).length, monthHours: sumH(inR(moStart, moEnd)),',
  '        weekEntries: inR(wkStart, wkEnd).length, weekHours: sumH(inR(wkStart, wkEnd)),',
  '        todayEntries: inR(today, today).length,',
  '        streak,',
  '        categories: [...catMap.values()].sort((a, b) => b.count - a.count),',
  '        monthly: [...monthMap.values()].sort((a, b) => a.month.localeCompare(b.month)),',
  '        status: [...statusMap.entries()].map(([name, count]) => ({ name, count })),',
  '      });',
  '    }',
  '',
  '    // ── DATA ─────────────────────────────────────────────',
  '    if (action === "data.backup") {',
  '      const { data: entries } = await sb.from("entries").select("*").order("date");',
  '      const { data: categories } = await sb.from("categories").select("*").order("sort");',
  '      return res.json({ exportedAt: new Date().toISOString(), version: 2, entries: (entries || []).map(rowToEntry), categories: categories || [] });',
  '    }',
  '',
  '    if (action === "data.restore") {',
  '      const { entries = [], categories = [], mode = "merge" } = req.body || {};',
  '      if (mode === "replace") {',
  '        await sb.from("entries").delete().neq("id", 0);',
  '        await sb.from("categories").delete().neq("id", 0);',
  '      }',
  '      if (entries.length) await sb.from("entries").insert(entries.map(bodyToRow));',
  '      if (categories.length) {',
  '        const rows = categories.map((c, i) => ({ name: c.name, color: c.color || "#64748b", sort: c.sort ?? i }));',
  '        await sb.from("categories").upsert(rows, { onConflict: "name" });',
  '      }',
  '      const { count } = await sb.from("entries").select("*", { count: "exact", head: true });',
  '      return res.json({ ok: true, entries: count });',
  '    }',
  '',
  '    if (action === "data.import-csv") {',
  '      const { csv } = req.body || {};',
  '      if (!csv) return res.status(400).json({ error: "csv required" });',
  '      const rows = parseCsv(csv);',
  '      if (rows.length < 2) return res.json({ ok: true, inserted: 0 });',
  '      const header = rows[0].map((h) => h.trim());',
  '      const idx = Object.fromEntries(header.map((h, i) => [h, i]));',
  '      const toInsert = [];',
  '      for (let i = 1; i < rows.length; i++) {',
  '        const r = rows[i];',
  '        if (!r[idx.date]) continue;',
  '        toInsert.push({',
  '          date: r[idx.date],',
  '          title: r[idx.title] || "Untitled",',
  '          description: r[idx.description] || "",',
  '          category: r[idx.category] || "Other",',
  '          project: r[idx.project] || "",',
  '          hours: Number(r[idx.hours]) || 0,',
  '          status: r[idx.status] || "Completed",',
  '          is_highlight: (r[idx.isHighlight] || "").toLowerCase() === "true" || r[idx.isHighlight] === "1",',
  '          links: r[idx.links] ? [r[idx.links]] : [],',
  '        });',
  '      }',
  '      if (toInsert.length) await sb.from("entries").insert(toInsert);',
  '      return res.json({ ok: true, inserted: toInsert.length });',
  '    }',
  '',
  '    // Unknown action',
  '    return res.status(404).json({ error: `Unknown action: ${action}` });',
  '  } catch (err) {',
  '    console.error("[api error]", err);',
  '    return res.status(500).json({ error: err.message, stack: (err.stack || "").split("\\n").slice(0, 5) });',
  '  }',
  '}',
  '',
  '// ─── CSV parser ───',
  'function parseCsv(text) {',
  '  const rows = [];',
  '  let row = [], cur = "", inQ = false;',
  '  for (let i = 0; i < text.length; i++) {',
  '    const c = text[i];',
  '    if (inQ) {',
  '      if (c === \'"\' && text[i + 1] === \'"\') { cur += \'"\'; i++; }',
  '      else if (c === \'"\') inQ = false;',
  '      else cur += c;',
  '    } else {',
  '      if (c === \'"\') inQ = true;',
  '      else if (c === ",") { row.push(cur); cur = ""; }',
  '      else if (c === "\\n") { row.push(cur); rows.push(row); row = []; cur = ""; }',
  '      else if (c !== "\\r") cur += c;',
  '    }',
  '  }',
  '  if (cur !== "" || row.length) { row.push(cur); rows.push(row); }',
  '  return rows;',
  '}',
  ''
));

// ═════════════════════════════════════════════════════════════
// FRONTEND
// ═════════════════════════════════════════════════════════════

file('src/styles/index.css', S(
  '@tailwind base;',
  '@tailwind components;',
  '@tailwind utilities;',
  '',
  ':root {',
  '  --bg: 250 250 249;',
  '  --panel: 255 255 255;',
  '  --border: 231 229 228;',
  '  --text: 28 25 23;',
  '  --muted: 120 113 108;',
  '  --accent: 59 130 246;',
  '}',
  '.dark {',
  '  --bg: 15 15 17;',
  '  --panel: 24 24 27;',
  '  --border: 39 39 42;',
  '  --text: 244 244 245;',
  '  --muted: 161 161 170;',
  '  --accent: 96 165 250;',
  '}',
  'html, body, #root { height: 100%; }',
  'body { background: rgb(var(--bg)); color: rgb(var(--text)); font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; }',
  '.md h1 { font-size: 1.25rem; font-weight: 700; margin: .5rem 0; }',
  '.md h2 { font-size: 1.1rem; font-weight: 700; margin: .5rem 0; }',
  '.md h3 { font-weight: 600; margin: .4rem 0; }',
  '.md p  { margin: .35rem 0; }',
  '.md ul { list-style: disc; padding-left: 1.25rem; margin: .35rem 0; }',
  '.md ol { list-style: decimal; padding-left: 1.25rem; margin: .35rem 0; }',
  '.md code { background: rgb(var(--border)); padding: 0 .25rem; border-radius: .25rem; font-size: .85em; }',
  '.md pre  { background: rgb(var(--border)); padding: .75rem; border-radius: .5rem; overflow-x: auto; }',
  '.md a { color: rgb(var(--accent)); text-decoration: underline; }',
  '.line-clamp-2 { display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }',
  ''
));

file('src/main.jsx', S(
  "import React from 'react';",
  "import ReactDOM from 'react-dom/client';",
  "import { BrowserRouter } from 'react-router-dom';",
  "import App from './App.jsx';",
  "import { ThemeProvider } from './context/ThemeContext.jsx';",
  "import { AuthProvider } from './context/AuthContext.jsx';",
  "import './styles/index.css';",
  '',
  "ReactDOM.createRoot(document.getElementById('root')).render(",
  '  <React.StrictMode>',
  '    <BrowserRouter>',
  '      <ThemeProvider>',
  '        <AuthProvider>',
  '          <App />',
  '        </AuthProvider>',
  '      </ThemeProvider>',
  '    </BrowserRouter>',
  '  </React.StrictMode>',
  ');',
  ''
));

file('src/context/ThemeContext.jsx', S(
  "import { createContext, useContext, useEffect, useState } from 'react';",
  'const Ctx = createContext(null);',
  'export function ThemeProvider({ children }) {',
  "  const [theme, setTheme] = useState(() => localStorage.getItem('iwp.theme') || 'light');",
  '  useEffect(() => {',
  '    const root = document.documentElement;',
  "    if (theme === 'dark') root.classList.add('dark'); else root.classList.remove('dark');",
  "    localStorage.setItem('iwp.theme', theme);",
  '  }, [theme]);',
  '  return <Ctx.Provider value={{ theme, toggle: () => setTheme((t) => (t === "dark" ? "light" : "dark")) }}>{children}</Ctx.Provider>;',
  '}',
  'export const useTheme = () => useContext(Ctx);',
  ''
));

file('src/context/AuthContext.jsx', S(
  "import { createContext, useContext, useState } from 'react';",
  'const Ctx = createContext(null);',
  "const KEY = 'iwp.password';",
  'export function AuthProvider({ children }) {',
  "  const [password, setPassword] = useState(() => localStorage.getItem(KEY) || '');",
  "  const [error, setError] = useState('');",
  '  const login = async (pw) => {',
  "    setError('');",
  '    try {',
  "      const r = await fetch('/api?action=stats.recent&limit=1', { headers: { 'x-app-password': pw } });",
  "      if (r.status === 401) { setError('Wrong password'); return false; }",
  '      if (!r.ok) { setError("Server error: " + r.status); return false; }',
  '      localStorage.setItem(KEY, pw);',
  '      setPassword(pw);',
  '      return true;',
  '    } catch (e) { setError("Network error: " + e.message); return false; }',
  '  };',
  "  const logout = () => { localStorage.removeItem(KEY); setPassword(''); };",
  '  return <Ctx.Provider value={{ password, login, logout, error }}>{children}</Ctx.Provider>;',
  '}',
  'export const useAuth = () => useContext(Ctx);',
  ''
));

file('src/api/client.js', S(
  "import { useAuth } from '../context/AuthContext.jsx';",
  '',
  'export function useApi() {',
  '  const { password } = useAuth();',
  "  const headers = { 'Content-Type': 'application/json', 'x-app-password': password || '' };",
  '',
  '  const call = async (action, params = {}, body) => {',
  "    const qs = new URLSearchParams({ action, ...params }).toString();",
  '    const r = await fetch("/api?" + qs, {',
  '      method: body ? "POST" : (action.includes("delete") || action.includes("star") || action.includes("update") || action.includes("save") || action.includes("clear") || action.includes("restore") || action.includes("import") || action.includes("duplicate") || action.includes("create") ? "POST" : "GET"),',
  '      headers,',
  '      body: body ? JSON.stringify(body) : undefined,',
  '    });',
  '    if (!r.ok) {',
  '      const err = await r.json().catch(() => ({}));',
  '      throw new Error(err.error || ("HTTP " + r.status));',
  '    }',
  '    return r.json();',
  '  };',
  '',
  '  return {',
  '    listEntries: (params = {}) => call("entries.list", params),',
  '    createEntry: (b) => call("entries.create", {}, b),',
  '    updateEntry: (id, b) => call("entries.update", { id }, b),',
  '    deleteEntry: (id) => call("entries.delete", { id }),',
  '    duplicate:   (id, b = {}) => call("entries.duplicate", { id }, b),',
  '    toggleStar:  (id) => call("entries.star", { id }),',
  '    getDraft:    () => call("draft.get"),',
  '    saveDraft:   (b) => call("draft.save", {}, b),',
  '    clearDraft:  () => call("draft.clear"),',
  '    listCategories: () => call("categories.list"),',
  '    createCategory: (b) => call("categories.create", {}, b),',
  '    updateCategory: (id, b) => call("categories.update", { id }, b),',
  '    deleteCategory: (id) => call("categories.delete", { id }),',
  '    listProjects: () => call("projects.list"),',
  '    projectNames: () => call("projects.names"),',
  '    statsSummary: (year) => call("stats.summary", { year: year || new Date().getFullYear() }),',
  '    statsRecent: (limit = 5) => call("stats.recent", { limit }),',
  '    restore: (b) => call("data.restore", {}, b),',
  '    importCsv: (csv) => call("data.import-csv", {}, { csv }),',
  '  };',
  '}',
  ''
));

file('src/App.jsx', S(
  "import { Routes, Route, Navigate } from 'react-router-dom';",
  "import { useAuth } from './context/AuthContext.jsx';",
  "import Layout from './components/Layout.jsx';",
  "import Login from './pages/Login.jsx';",
  "import Dashboard from './pages/Dashboard.jsx';",
  "import Timeline from './pages/Timeline.jsx';",
  "import Projects from './pages/Projects.jsx';",
  "import Report from './pages/Report.jsx';",
  "import Settings from './pages/Settings.jsx';",
  '',
  'export default function App() {',
  '  const { password } = useAuth();',
  '  if (!password) return <Login />;',
  '  return (',
  '    <Layout>',
  '      <Routes>',
  '        <Route path="/" element={<Navigate to="/dashboard" replace />} />',
  '        <Route path="/dashboard" element={<Dashboard />} />',
  '        <Route path="/timeline" element={<Timeline />} />',
  '        <Route path="/projects" element={<Projects />} />',
  '        <Route path="/report" element={<Report />} />',
  '        <Route path="/settings" element={<Settings />} />',
  '        <Route path="*" element={<Navigate to="/dashboard" replace />} />',
  '      </Routes>',
  '    </Layout>',
  '  );',
  '}',
  ''
));

file('src/pages/Login.jsx', S(
  "import { useState } from 'react';",
  "import { useAuth } from '../context/AuthContext.jsx';",
  '',
  'export default function Login() {',
  '  const { login, error } = useAuth();',
  '  const [pw, setPw] = useState("");',
  '  const [busy, setBusy] = useState(false);',
  '  const onSubmit = async (e) => { e.preventDefault(); setBusy(true); await login(pw); setBusy(false); };',
  '  return (',
  '    <div className="min-h-screen flex items-center justify-center p-6">',
  '      <form onSubmit={onSubmit} className="w-full max-w-sm bg-panel border border-border rounded-xl p-6 space-y-4">',
  '        <h1 className="text-xl font-semibold">📓 IWP Work Tracker</h1>',
  '        <p className="text-sm text-muted">Enter your app password.</p>',
  '        <input type="password" autoFocus value={pw} onChange={(e) => setPw(e.target.value)}',
  '          className="w-full rounded-md border border-border bg-bg px-3 py-2 outline-none focus:ring-2 focus:ring-accent" placeholder="Password" />',
  '        {error && <div className="text-sm text-red-500">{error}</div>}',
  '        <button disabled={busy} className="w-full rounded-md bg-accent text-white py-2 font-medium hover:opacity-90 disabled:opacity-50">',
  '          {busy ? "Checking…" : "Unlock"}',
  '        </button>',
  '        <div className="text-xs text-muted text-center">',
  '          First time? Use the APP_PASSWORD from your .env file.',
  '        </div>',
  '      </form>',
  '    </div>',
  '  );',
  '}',
  ''
));

file('src/components/Layout.jsx', S(
  "import { NavLink, useNavigate } from 'react-router-dom';",
  "import { useTheme } from '../context/ThemeContext.jsx';",
  "import { useAuth } from '../context/AuthContext.jsx';",
  "import { useState } from 'react';",
  "import EntryForm from './EntryForm.jsx';",
  '',
  'const nav = [',
  '  { to: "/dashboard", label: "Dashboard" },',
  '  { to: "/timeline",  label: "Timeline" },',
  '  { to: "/projects",  label: "Projects" },',
  '  { to: "/report",    label: "Report" },',
  '  { to: "/settings",  label: "Settings" },',
  '];',
  '',
  'export default function Layout({ children }) {',
  '  const { theme, toggle } = useTheme();',
  '  const { logout } = useAuth();',
  '  const [showForm, setShowForm] = useState(false);',
  '  const nav2 = useNavigate();',
  '  return (',
  '    <div className="min-h-screen flex flex-col md:flex-row">',
  '      <aside className="md:w-56 md:min-h-screen border-b md:border-b-0 md:border-r border-border bg-panel">',
  '        <div className="p-4 flex md:block items-center justify-between">',
  '          <div className="font-semibold">📓 IWP Tracker</div>',
  '          <div className="flex md:hidden gap-2">',
  '            <button onClick={toggle} className="text-sm px-2 py-1 rounded border border-border">{theme === "dark" ? "☀️" : "🌙"}</button>',
  '          </div>',
  '        </div>',
  '        <nav className="px-2 pb-3 flex md:flex-col gap-1 overflow-x-auto">',
  '          {nav.map((n) => (',
  '            <NavLink key={n.to} to={n.to}',
  '              className={({ isActive }) => "px-3 py-2 rounded-md text-sm whitespace-nowrap " + (isActive ? "bg-accent/10 text-accent font-medium" : "hover:bg-border/50 text-muted")}>',
  '              {n.label}',
  '            </NavLink>',
  '          ))}',
  '        </nav>',
  '        <div className="hidden md:flex flex-col gap-2 px-4 py-3 border-t border-border">',
  '          <button onClick={toggle} className="text-sm text-left text-muted hover:text-text">',
  '            {theme === "dark" ? "☀️  Light mode" : "🌙  Dark mode"}',
  '          </button>',
  '          <button onClick={() => { logout(); nav2("/"); }} className="text-sm text-left text-muted hover:text-text">🚪  Lock</button>',
  '        </div>',
  '      </aside>',
  '      <main className="flex-1 relative">',
  '        <div className="max-w-4xl mx-auto p-4 md:p-8 pb-28">{children}</div>',
  '        <button onClick={() => setShowForm(true)}',
  '          className="fixed bottom-6 right-6 z-30 rounded-full bg-accent text-white px-5 py-3 font-medium shadow-lg hover:opacity-90">',
  '          ＋ Log Work',
  '        </button>',
  '        {showForm && (',
  '          <EntryForm onClose={() => setShowForm(false)}',
  '            onSaved={() => { setShowForm(false); window.dispatchEvent(new Event("entries:changed")); }} />',
  '        )}',
  '      </main>',
  '    </div>',
  '  );',
  '}',
  ''
));

file('src/components/EntryForm.jsx', S(
  "import { useEffect, useRef, useState } from 'react';",
  "import ReactMarkdown from 'react-markdown';",
  "import { useApi } from '../api/client.js';",
  '',
  'const STATUSES = ["Completed", "In Progress", "Blocked"];',
  '',
  'export default function EntryForm({ entry, onClose, onSaved }) {',
  '  const api = useApi();',
  '  const [categories, setCategories] = useState([]);',
  '  const [projectNames, setProjectNames] = useState([]);',
  '  const [form, setForm] = useState(() => entry || {',
  '    date: new Date().toISOString().slice(0, 10),',
  '    title: "", description: "", category: "Development", project: "",',
  '    hours: "", status: "Completed", isHighlight: false, links: [],',
  '  });',
  '  const [linkInput, setLinkInput] = useState("");',
  '  const [preview, setPreview] = useState(false);',
  '  const [saving, setSaving] = useState(false);',
  '  const [error, setError] = useState("");',
  '  const titleRef = useRef(null);',
  '',
  '  useEffect(() => {',
  '    api.listCategories().then(setCategories).catch(() => {});',
  '    api.projectNames().then(setProjectNames).catch(() => {});',
  '    if (!entry) {',
  '      api.getDraft().then(({ payload }) => {',
  '        if (payload && (payload.title || payload.description)) {',
  '          setForm((f) => ({ ...f, ...payload, date: new Date().toISOString().slice(0, 10) }));',
  '        }',
  '      }).catch(() => {});',
  '    }',
  '    setTimeout(() => { if (titleRef.current) titleRef.current.focus(); }, 50);',
  '  }, []);',
  '',
  '  useEffect(() => {',
  '    if (entry) return;',
  '    const t = setTimeout(() => { api.saveDraft(form).catch(() => {}); }, 800);',
  '    return () => clearTimeout(t);',
  '  }, [form]);',
  '',
  '  const set = (k, v) => setForm((f) => ({ ...f, [k]: v }));',
  '',
  '  const submit = async () => {',
  '    setSaving(true); setError("");',
  '    try {',
  '      const payload = { ...form, hours: Number(form.hours) || 0, links: form.links || [] };',
  '      if (entry && entry.id) await api.updateEntry(entry.id, payload);',
  '      else { await api.createEntry(payload); await api.clearDraft().catch(() => {}); }',
  '      if (onSaved) onSaved();',
  '    } catch (e) { setError(e.message); }',
  '    finally { setSaving(false); }',
  '  };',
  '',
  '  const onKeyDown = (e) => {',
  '    if ((e.ctrlKey || e.metaKey) && e.key === "Enter") { e.preventDefault(); submit(); }',
  '    if (e.key === "Escape" && !saving && onClose) onClose();',
  '  };',
  '',
  '  const addLink = () => {',
  '    if (!linkInput.trim()) return;',
  '    set("links", [...(form.links || []), linkInput.trim()]);',
  '    setLinkInput("");',
  '  };',
  '',
  '  return (',
  '    <div className="fixed inset-0 z-40 bg-black/40 flex items-start justify-center p-4 overflow-y-auto" onKeyDown={onKeyDown}>',
  '      <div className="w-full max-w-2xl bg-panel border border-border rounded-xl shadow-xl my-8">',
  '        <div className="flex items-center justify-between px-4 py-3 border-b border-border">',
  '          <h2 className="font-semibold">{entry ? "Edit Entry" : "Log Work"}</h2>',
  '          <div className="flex items-center gap-2">',
  '            <button onClick={() => set("isHighlight", !form.isHighlight)} title="Mark as highlight"',
  '              className={"text-lg " + (form.isHighlight ? "text-yellow-500" : "text-muted")}>',
  '              {form.isHighlight ? "★" : "☆"}',
  '            </button>',
  '            <button onClick={onClose} className="text-muted hover:text-text text-xl leading-none">×</button>',
  '          </div>',
  '        </div>',
  '        <div className="p-4 space-y-3">',
  '          <div className="grid grid-cols-2 gap-3">',
  '            <label className="text-sm"><div className="text-muted mb-1">Date</div>',
  '              <input type="date" value={form.date} onChange={(e) => set("date", e.target.value)}',
  '                className="w-full rounded-md border border-border bg-bg px-3 py-2 outline-none focus:ring-2 focus:ring-accent" /></label>',
  '            <label className="text-sm"><div className="text-muted mb-1">Status</div>',
  '              <select value={form.status} onChange={(e) => set("status", e.target.value)}',
  '                className="w-full rounded-md border border-border bg-bg px-3 py-2 outline-none focus:ring-2 focus:ring-accent">',
  '                {STATUSES.map((s) => <option key={s}>{s}</option>)}',
  '              </select></label>',
  '          </div>',
  '          <label className="block text-sm"><div className="text-muted mb-1">Title</div>',
  '            <input ref={titleRef} value={form.title} onChange={(e) => set("title", e.target.value)} placeholder="What did you do?"',
  '              className="w-full rounded-md border border-border bg-bg px-3 py-2 outline-none focus:ring-2 focus:ring-accent" /></label>',
  '          <div className="text-sm">',
  '            <div className="flex items-center justify-between mb-1">',
  '              <div className="text-muted">Description (Markdown)</div>',
  '              <button onClick={() => setPreview((p) => !p)} className="text-xs text-accent">{preview ? "Edit" : "Preview"}</button>',
  '            </div>',
  '            {preview ? (',
  '              <div className="md min-h-[100px] rounded-md border border-border bg-bg px-3 py-2">',
  '                <ReactMarkdown>{form.description || "_No description_"}</ReactMarkdown>',
  '              </div>',
  '            ) : (',
  '              <textarea rows={6} value={form.description} onChange={(e) => set("description", e.target.value)}',
  '                placeholder="Details, links, decisions, blockers…"',
  '                className="w-full rounded-md border border-border bg-bg px-3 py-2 outline-none focus:ring-2 focus:ring-accent font-mono text-sm" />',
  '            )}',
  '          </div>',
  '          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">',
  '            <label className="text-sm"><div className="text-muted mb-1">Category</div>',
  '              <select value={form.category} onChange={(e) => set("category", e.target.value)}',
  '                className="w-full rounded-md border border-border bg-bg px-3 py-2 outline-none focus:ring-2 focus:ring-accent">',
  '                {categories.map((c) => <option key={c.id} value={c.name}>{c.name}</option>)}',
  '              </select></label>',
  '            <label className="text-sm sm:col-span-2"><div className="text-muted mb-1">Project / Tag</div>',
  '              <input list="project-names" value={form.project} onChange={(e) => set("project", e.target.value)} placeholder="e.g. IWP Tracker"',
  '                className="w-full rounded-md border border-border bg-bg px-3 py-2 outline-none focus:ring-2 focus:ring-accent" />',
  '              <datalist id="project-names">{projectNames.map((p) => <option key={p.name} value={p.name} />)}</datalist></label>',
  '          </div>',
  '          <div className="grid grid-cols-2 gap-3">',
  '            <label className="text-sm"><div className="text-muted mb-1">Hours</div>',
  '              <input type="number" step="0.25" min="0" value={form.hours} onChange={(e) => set("hours", e.target.value)} placeholder="0"',
  '                className="w-full rounded-md border border-border bg-bg px-3 py-2 outline-none focus:ring-2 focus:ring-accent" /></label>',
  '          </div>',
  '          <div className="text-sm">',
  '            <div className="text-muted mb-1">Links</div>',
  '            <div className="flex gap-2">',
  '              <input value={linkInput} onChange={(e) => setLinkInput(e.target.value)}',
  '                onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); addLink(); } }} placeholder="https://…"',
  '                className="flex-1 rounded-md border border-border bg-bg px-3 py-2 outline-none focus:ring-2 focus:ring-accent" />',
  '              <button onClick={addLink} type="button" className="rounded-md border border-border px-3">Add</button>',
  '            </div>',
  '            {(form.links || []).length > 0 && (',
  '              <ul className="mt-2 space-y-1">',
  '                {form.links.map((l, i) => (',
  '                  <li key={i} className="flex items-center gap-2 text-xs">',
  '                    <a className="text-accent underline truncate flex-1" href={l} target="_blank" rel="noreferrer">{l}</a>',
  '                    <button onClick={() => set("links", form.links.filter((_, j) => j !== i))} className="text-muted hover:text-red-500">×</button>',
  '                  </li>',
  '                ))}',
  '              </ul>',
  '            )}',
  '          </div>',
  '          {error && <div className="text-sm text-red-500">Error: {error}</div>}',
  '        </div>',
  '        <div className="flex items-center justify-between px-4 py-3 border-t border-border">',
  '          <div className="text-xs text-muted">Ctrl/⌘ + Enter to save</div>',
  '          <div className="flex gap-2">',
  '            <button onClick={onClose} className="rounded-md border border-border px-4 py-2 text-sm">Cancel</button>',
  '            <button onClick={submit} disabled={saving}',
  '              className="rounded-md bg-accent text-white px-4 py-2 text-sm font-medium disabled:opacity-50">',
  '              {saving ? "Saving…" : entry ? "Update" : "Save"}',
  '            </button>',
  '          </div>',
  '        </div>',
  '      </div>',
  '    </div>',
  '  );',
  '}',
  ''
));

file('src/components/EntryCard.jsx', S(
  "import { useState } from 'react';",
  "import ReactMarkdown from 'react-markdown';",
  "import { useApi } from '../api/client.js';",
  '',
  'export default function EntryCard({ entry, onChanged, onEdit }) {',
  '  const api = useApi();',
  '  const [expanded, setExpanded] = useState(false);',
  '  const star = async () => { await api.toggleStar(entry.id); if (onChanged) onChanged(); };',
  '  const del = async () => { if (confirm("Delete this entry?")) { await api.deleteEntry(entry.id); if (onChanged) onChanged(); } };',
  '  const dup = async () => { await api.duplicate(entry.id); if (onChanged) onChanged(); };',
  '  return (',
  '    <div className="rounded-lg border border-border bg-panel p-4 hover:shadow-sm transition">',
  '      <div className="flex items-start gap-3">',
  '        <button onClick={star} title="Highlight" className={"text-lg leading-none " + (entry.isHighlight ? "text-yellow-500" : "text-muted hover:text-yellow-500")}>',
  '          {entry.isHighlight ? "★" : "☆"}',
  '        </button>',
  '        <div className="flex-1 min-w-0">',
  '          <div className="flex items-baseline gap-2 flex-wrap">',
  '            <h3 className="font-medium truncate">{entry.title}</h3>',
  '            {entry.status !== "Completed" && (',
  '              <span className="text-xs px-2 py-0.5 rounded-full border border-border text-muted">{entry.status}</span>',
  '            )}',
  '          </div>',
  '          <div className="text-xs text-muted mt-1 flex items-center gap-2 flex-wrap">',
  '            <span>{entry.date}</span><span>·</span><span>{entry.category}</span>',
  '            {entry.project && <><span>·</span><span>{entry.project}</span></>}',
  '            {entry.hours > 0 && <><span>·</span><span>{entry.hours}h</span></>}',
  '          </div>',
  '          {entry.description && (',
  '            <div className={"md text-sm mt-2 " + (expanded ? "" : "line-clamp-2")}>',
  '              <ReactMarkdown>{entry.description}</ReactMarkdown>',
  '            </div>',
  '          )}',
  '          {entry.links && entry.links.length > 0 && (',
  '            <div className="mt-2 flex flex-wrap gap-2">',
  '              {entry.links.map((l, i) => (',
  '                <a key={i} href={l} target="_blank" rel="noreferrer" className="text-xs text-accent underline truncate max-w-[200px]">{l}</a>',
  '              ))}',
  '            </div>',
  '          )}',
  '          <div className="mt-3 flex items-center gap-3 text-xs text-muted">',
  '            {entry.description && <button onClick={() => setExpanded((e) => !e)} className="hover:text-text">{expanded ? "Show less" : "Show more"}</button>}',
  '            <button onClick={() => onEdit && onEdit(entry)} className="hover:text-text">Edit</button>',
  '            <button onClick={dup} className="hover:text-text">Duplicate</button>',
  '            <button onClick={del} className="hover:text-red-500">Delete</button>',
  '          </div>',
  '        </div>',
  '      </div>',
  '    </div>',
  '  );',
  '}',
  ''
));

file('src/components/Filters.jsx', S(
  'export default function Filters({ value, onChange, categories, projects }) {',
  '  const set = (k, v) => onChange({ ...value, [k]: v });',
  '  return (',
  '    <div className="grid grid-cols-2 md:grid-cols-6 gap-2 text-sm">',
  '      <input type="date" value={value.from || ""} onChange={(e) => set("from", e.target.value)}',
  '        className="rounded-md border border-border bg-panel px-3 py-2 col-span-2 md:col-span-1" placeholder="From" />',
  '      <input type="date" value={value.to || ""} onChange={(e) => set("to", e.target.value)}',
  '        className="rounded-md border border-border bg-panel px-3 py-2 col-span-2 md:col-span-1" placeholder="To" />',
  '      <select value={value.category || ""} onChange={(e) => set("category", e.target.value)}',
  '        className="rounded-md border border-border bg-panel px-3 py-2">',
  '        <option value="">All categories</option>',
  '        {categories.map((c) => <option key={c.id} value={c.name}>{c.name}</option>)}',
  '      </select>',
  '      <select value={value.project || ""} onChange={(e) => set("project", e.target.value)}',
  '        className="rounded-md border border-border bg-panel px-3 py-2">',
  '        <option value="">All projects</option>',
  '        {projects.map((p) => <option key={p.name} value={p.name}>{p.name}</option>)}',
  '      </select>',
  '      <select value={value.status || ""} onChange={(e) => set("status", e.target.value)}',
  '        className="rounded-md border border-border bg-panel px-3 py-2">',
  '        <option value="">All statuses</option>',
  '        <option>Completed</option><option>In Progress</option><option>Blocked</option>',
  '      </select>',
  '      <label className="flex items-center gap-2 px-3 py-2 rounded-md border border-border bg-panel">',
  '        <input type="checkbox" checked={value.highlight === "true"} onChange={(e) => set("highlight", e.target.checked ? "true" : "")} />',
  '        ★ Only',
  '      </label>',
  '    </div>',
  '  );',
  '}',
  ''
));

file('src/components/charts/CategoryPie.jsx', S(
  "import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer, Legend } from 'recharts';",
  "const COLORS = ['#3b82f6','#a855f7','#f59e0b','#10b981','#06b6d4','#64748b','#ec4899','#8b5cf6','#94a3b8'];",
  'export default function CategoryPie({ data }) {',
  '  return (',
  '    <ResponsiveContainer width="100%" height={260}>',
  '      <PieChart>',
  '        <Pie data={data} dataKey="count" nameKey="name" outerRadius={90} innerRadius={50} paddingAngle={2}>',
  '          {data.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}',
  '        </Pie>',
  '        <Tooltip />',
  '        <Legend />',
  '      </PieChart>',
  '    </ResponsiveContainer>',
  '  );',
  '}',
  ''
));

file('src/components/charts/MonthlyBar.jsx', S(
  "import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';",
  "export default function MonthlyBar({ data, dataKey = 'count' }) {",
  '  return (',
  '    <ResponsiveContainer width="100%" height={260}>',
  '      <BarChart data={data}>',
  '        <CartesianGrid strokeDasharray="3 3" opacity={0.15} />',
  '        <XAxis dataKey="month" fontSize={12} />',
  '        <YAxis fontSize={12} allowDecimals={false} />',
  '        <Tooltip />',
  '        <Bar dataKey={dataKey} fill="#3b82f6" radius={[4, 4, 0, 0]} />',
  '      </BarChart>',
  '    </ResponsiveContainer>',
  '  );',
  '}',
  ''
));

file('src/pages/Dashboard.jsx', S(
  "import { useEffect, useState } from 'react';",
  "import { useApi } from '../api/client.js';",
  "import CategoryPie from '../components/charts/CategoryPie.jsx';",
  "import MonthlyBar from '../components/charts/MonthlyBar.jsx';",
  "import EntryCard from '../components/EntryCard.jsx';",
  "import EntryForm from '../components/EntryForm.jsx';",
  '',
  'function Stat({ label, value }) {',
  '  return (',
  '    <div className="rounded-lg border border-border bg-panel p-4">',
  '      <div className="text-xs uppercase tracking-wide text-muted">{label}</div>',
  '      <div className="text-2xl font-semibold mt-1">{value}</div>',
  '    </div>',
  '  );',
  '}',
  '',
  'export default function Dashboard() {',
  '  const api = useApi();',
  '  const [stats, setStats] = useState(null);',
  '  const [recent, setRecent] = useState([]);',
  '  const [editing, setEditing] = useState(null);',
  '  const [error, setError] = useState("");',
  '',
  '  const load = async () => {',
  '    try {',
  '      setError("");',
  '      const [s, r] = await Promise.all([api.statsSummary(), api.statsRecent(5)]);',
  '      setStats(s); setRecent(r);',
  '    } catch (e) { setError(e.message); }',
  '  };',
  '  useEffect(() => { load(); }, []);',
  '  useEffect(() => {',
  '    const h = () => load();',
  '    window.addEventListener("entries:changed", h);',
  '    return () => window.removeEventListener("entries:changed", h);',
  '  }, []);',
  '',
  '  if (error) return <div className="p-8 text-red-500">Error loading dashboard: {error}</div>;',
  '  if (!stats) return <div className="p-8 text-muted">Loading…</div>;',
  '',
  '  const today = new Date().toISOString().slice(0, 10);',
  '  const hasToday = recent.some((e) => e.date === today) || stats.todayEntries > 0;',
  '',
  '  return (',
  '    <div className="space-y-6">',
  '      <div>',
  '        <h1 className="text-2xl font-semibold">Dashboard</h1>',
  '        <p className="text-sm text-muted">Your {stats.year} at a glance.</p>',
  '      </div>',
  '      {!hasToday && (',
  '        <div className="rounded-lg border border-yellow-500/40 bg-yellow-500/10 text-yellow-700 dark:text-yellow-300 px-4 py-3 text-sm">',
  '          You haven\'t logged anything today yet. Tap the ＋ Log Work button.',
  '        </div>',
  '      )}',
  '      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">',
  '        <Stat label="This year" value={stats.yearEntries} />',
  '        <Stat label="This month" value={stats.monthEntries} />',
  '        <Stat label="This week" value={stats.weekEntries} />',
  '        <Stat label="Streak (days)" value={stats.streak} />',
  '        <Stat label="Hours this year" value={stats.yearHours.toFixed(1)} />',
  '        <Stat label="Hours this month" value={stats.monthHours.toFixed(1)} />',
  '        <Stat label="Hours this week" value={stats.weekHours.toFixed(1)} />',
  '        <Stat label="Today" value={stats.todayEntries} />',
  '      </div>',
  '      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">',
  '        <div className="rounded-lg border border-border bg-panel p-4">',
  '          <h2 className="font-medium mb-2">Category breakdown</h2>',
  '          {stats.categories.length ? <CategoryPie data={stats.categories} /> : <div className="text-muted text-sm">No data yet.</div>}',
  '        </div>',
  '        <div className="rounded-lg border border-border bg-panel p-4">',
  '          <h2 className="font-medium mb-2">Monthly activity</h2>',
  '          {stats.monthly.length ? <MonthlyBar data={stats.monthly} /> : <div className="text-muted text-sm">No data yet.</div>}',
  '        </div>',
  '      </div>',
  '      <div>',
  '        <h2 className="font-medium mb-3">Recent entries</h2>',
  '        <div className="space-y-3">',
  '          {recent.map((e) => <EntryCard key={e.id} entry={e} onChanged={load} onEdit={setEditing} />)}',
  '          {!recent.length && <div className="text-muted text-sm">No entries yet.</div>}',
  '        </div>',
  '      </div>',
  '      {editing && <EntryForm entry={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); load(); }} />}',
  '    </div>',
  '  );',
  '}',
  ''
));

file('src/pages/Timeline.jsx', S(
  "import { useEffect, useMemo, useState } from 'react';",
  "import { useApi } from '../api/client.js';",
  "import EntryCard from '../components/EntryCard.jsx';",
  "import EntryForm from '../components/EntryForm.jsx';",
  "import Filters from '../components/Filters.jsx';",
  '',
  'export default function Timeline() {',
  '  const api = useApi();',
  '  const [entries, setEntries] = useState([]);',
  '  const [categories, setCategories] = useState([]);',
  '  const [projects, setProjects] = useState([]);',
  '  const [filters, setFilters] = useState({ from: "", to: "", category: "", project: "", status: "", highlight: "" });',
  '  const [q, setQ] = useState("");',
  '  const [editing, setEditing] = useState(null);',
  '',
  '  const load = () => {',
  '    const params = Object.fromEntries(Object.entries(filters).filter(([, v]) => v));',
  '    if (q) params.q = q;',
  '    api.listEntries(params).then(setEntries).catch(() => {});',
  '  };',
  '  useEffect(() => { load(); }, [filters, q]);',
  '  useEffect(() => {',
  '    api.listCategories().then(setCategories).catch(() => {});',
  '    api.projectNames().then(setProjects).catch(() => {});',
  '    const h = () => load();',
  '    window.addEventListener("entries:changed", h);',
  '    return () => window.removeEventListener("entries:changed", h);',
  '  }, []);',
  '',
  '  const grouped = useMemo(() => {',
  '    const map = new Map();',
  '    for (const e of entries) {',
  '      const m = e.date.slice(0, 7);',
  '      if (!map.has(m)) map.set(m, []);',
  '      map.get(m).push(e);',
  '    }',
  '    return [...map.entries()].sort((a, b) => b[0].localeCompare(a[0]));',
  '  }, [entries]);',
  '',
  '  return (',
  '    <div className="space-y-4">',
  '      <div className="flex items-center justify-between">',
  '        <h1 className="text-2xl font-semibold">Timeline</h1>',
  '        <div className="text-sm text-muted">{entries.length} entries</div>',
  '      </div>',
  '      <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search title, description, project…"',
  '        className="w-full rounded-md border border-border bg-panel px-3 py-2 outline-none focus:ring-2 focus:ring-accent" />',
  '      <Filters value={filters} onChange={setFilters} categories={categories} projects={projects} />',
  '      <div className="space-y-8 pt-2">',
  '        {grouped.map(([month, list]) => (',
  '          <section key={month}>',
  '            <h2 className="text-sm uppercase tracking-wide text-muted mb-2">{month}</h2>',
  '            <div className="space-y-3">',
  '              {list.map((e) => <EntryCard key={e.id} entry={e} onChanged={load} onEdit={setEditing} />)}',
  '            </div>',
  '          </section>',
  '        ))}',
  '        {!grouped.length && <div className="text-muted text-sm">No entries match your filters.</div>}',
  '      </div>',
  '      {editing && <EntryForm entry={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); load(); }} />}',
  '    </div>',
  '  );',
  '}',
  ''
));

file('src/pages/Projects.jsx', S(
  "import { useEffect, useState } from 'react';",
  "import { useApi } from '../api/client.js';",
  "import EntryCard from '../components/EntryCard.jsx';",
  "import EntryForm from '../components/EntryForm.jsx';",
  '',
  'export default function Projects() {',
  '  const api = useApi();',
  '  const [projects, setProjects] = useState([]);',
  '  const [open, setOpen] = useState(null);',
  '  const [entries, setEntries] = useState([]);',
  '  const [editing, setEditing] = useState(null);',
  '',
  '  useEffect(() => { api.listProjects().then(setProjects).catch(() => {}); }, []);',
  '',
  '  const loadEntries = async (name) => {',
  '    setOpen(name);',
  '    setEntries(await api.listEntries({ project: name }));',
  '  };',
  '  const refresh = () => { api.listProjects().then(setProjects).catch(() => {}); if (open) loadEntries(open); };',
  '',
  '  return (',
  '    <div className="space-y-6">',
  '      <h1 className="text-2xl font-semibold">Projects</h1>',
  '      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">',
  '        {projects.map((p) => (',
  '          <button key={p.project} onClick={() => loadEntries(p.project)}',
  '            className={"text-left rounded-lg border bg-panel p-4 hover:shadow-sm transition " + (open === p.project ? "border-accent" : "border-border")}>',
  '            <div className="font-medium truncate">{p.project}</div>',
  '            <div className="text-xs text-muted mt-1">',
  '              {p.entries} entries · {Number(p.hours).toFixed(1)}h · {p.highlights} ★',
  '            </div>',
  '            <div className="text-xs text-muted mt-1">{p.first_date} → {p.last_date}</div>',
  '          </button>',
  '        ))}',
  '        {!projects.length && <div className="text-muted text-sm">No projects yet — add a project name to an entry.</div>}',
  '      </div>',
  '      {open && (',
  '        <div className="space-y-3">',
  '          <div className="flex items-center justify-between">',
  '            <h2 className="font-medium">Entries in "{open}"</h2>',
  '            <button onClick={() => setOpen(null)} className="text-xs text-muted hover:text-text">Close</button>',
  '          </div>',
  '          {entries.map((e) => <EntryCard key={e.id} entry={e} onChanged={refresh} onEdit={setEditing} />)}',
  '        </div>',
  '      )}',
  '      {editing && <EntryForm entry={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); refresh(); }} />}',
  '    </div>',
  '  );',
  '}',
  ''
));

file('src/pages/Report.jsx', S(
  "import { useEffect, useMemo, useRef, useState } from 'react';",
  "import { useApi } from '../api/client.js';",
  "import CategoryPie from '../components/charts/CategoryPie.jsx';",
  "import MonthlyBar from '../components/charts/MonthlyBar.jsx';",
  '',
  'export default function Report() {',
  '  const api = useApi();',
  '  const thisYear = new Date().getFullYear();',
  '  const [from, setFrom] = useState(thisYear + "-01-01");',
  '  const [to, setTo] = useState(thisYear + "-12-31");',
  '  const [entries, setEntries] = useState([]);',
  '  const [busy, setBusy] = useState("");',
  '  const reportRef = useRef(null);',
  '',
  '  useEffect(() => { api.listEntries({ from, to }).then(setEntries).catch(() => {}); }, [from, to]);',
  '',
  '  const byCategory = useMemo(() => {',
  '    const m = new Map();',
  '    for (const e of entries) {',
  '      if (!m.has(e.category)) m.set(e.category, { name: e.category, count: 0, hours: 0, items: [] });',
  '      const a = m.get(e.category); a.count++; a.hours += e.hours || 0; a.items.push(e);',
  '    }',
  '    return [...m.values()].sort((a, b) => b.count - a.count);',
  '  }, [entries]);',
  '',
  '  const byProject = useMemo(() => {',
  '    const m = new Map();',
  '    for (const e of entries.filter((x) => x.project)) {',
  '      if (!m.has(e.project)) m.set(e.project, { name: e.project, count: 0, hours: 0, items: [] });',
  '      const a = m.get(e.project); a.count++; a.hours += e.hours || 0; a.items.push(e);',
  '    }',
  '    return [...m.values()].sort((a, b) => b.count - a.count);',
  '  }, [entries]);',
  '',
  '  const byMonth = useMemo(() => {',
  '    const m = new Map();',
  '    for (const e of entries) {',
  '      const k = e.date.slice(0, 7);',
  '      if (!m.has(k)) m.set(k, { month: k, count: 0, hours: 0 });',
  '      const a = m.get(k); a.count++; a.hours += e.hours || 0;',
  '    }',
  '    return [...m.values()].sort((a, b) => a.month.localeCompare(b.month));',
  '  }, [entries]);',
  '',
  '  const highlights = entries.filter((e) => e.isHighlight);',
  '  const totalHours = entries.reduce((s, e) => s + (e.hours || 0), 0);',
  '',
  '  const exportPdf = async () => {',
  '    setBusy("pdf");',
  '    try {',
  '      const { jsPDF } = await import("jspdf");',
  '      const html2canvas = (await import("html2canvas")).default;',
  '      const doc = new jsPDF({ unit: "pt", format: "a4" });',
  '      const pw = doc.internal.pageSize.getWidth();',
  '      const ph = doc.internal.pageSize.getHeight();',
  '      doc.setFontSize(28); doc.text("IWP Work Report", 40, 100);',
  '      doc.setFontSize(14); doc.text(from + "  →  " + to, 40, 130);',
  '      doc.setFontSize(12);',
  '      doc.text("Total entries: " + entries.length, 40, 170);',
  '      doc.text("Total hours: " + totalHours.toFixed(1), 40, 190);',
  '      doc.text("Highlights: " + highlights.length, 40, 210);',
  '      if (reportRef.current) {',
  '        const canvas = await html2canvas(reportRef.current, { scale: 2, backgroundColor: "#fff" });',
  '        const img = canvas.toDataURL("image/png");',
  '        const iw = pw - 80; const ih = (canvas.height * iw) / canvas.width;',
  '        doc.addPage();',
  '        let y = 40;',
  '        if (y + ih > ph - 40) { doc.addPage(); y = 40; }',
  '        doc.addImage(img, "PNG", 40, y, iw, ih);',
  '      }',
  '      doc.save("iwp-report-" + from + "_" + to + ".pdf");',
  '    } finally { setBusy(""); }',
  '  };',
  '',
  '  const exportXlsx = async () => {',
  '    setBusy("xlsx");',
  '    try {',
  '      const XLSX = await import("xlsx");',
  '      const wb = XLSX.utils.book_new();',
  '      const rows = entries.map((e) => ({',
  '        Date: e.date, Title: e.title, Category: e.category, Project: e.project,',
  '        Hours: e.hours, Status: e.status, Highlight: e.isHighlight ? "Yes" : "",',
  '        Description: e.description, Links: (e.links || []).join(" | "),',
  '      }));',
  '      XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(rows), "Entries");',
  '      XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(byCategory.map((x) => ({ name: x.name, count: x.count, hours: x.hours }))), "By Category");',
  '      XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(byProject.map((x) => ({ name: x.name, count: x.count, hours: x.hours }))), "By Project");',
  '      XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(byMonth), "By Month");',
  '      XLSX.writeFile(wb, "iwp-report-" + from + "_" + to + ".xlsx");',
  '    } finally { setBusy(""); }',
  '  };',
  '',
  '  const exportMarkdown = () => {',
  '    const lines = [];',
  '    lines.push("# IWP Work Report", "", "**Range:** " + from + " → " + to, "");',
  '    lines.push("- Entries: **" + entries.length + "**");',
  '    lines.push("- Hours: **" + totalHours.toFixed(1) + "**");',
  '    lines.push("- Highlights: **" + highlights.length + "**", "");',
  '    if (highlights.length) {',
  '      lines.push("## Highlights", "");',
  '      for (const e of highlights) lines.push("- " + e.date + " — **" + e.title + "** (" + e.category + ")");',
  '      lines.push("");',
  '    }',
  '    lines.push("## By Category", "");',
  '    for (const c of byCategory) lines.push("- **" + c.name + "** — " + c.count + " entries, " + c.hours.toFixed(1) + "h");',
  '    lines.push("", "## By Project", "");',
  '    for (const p of byProject) lines.push("- **" + p.name + "** — " + p.count + " entries, " + p.hours.toFixed(1) + "h");',
  '    lines.push("", "## Month-by-month", "");',
  '    for (const m of byMonth) lines.push("- " + m.month + ": " + m.count + " entries, " + m.hours.toFixed(1) + "h");',
  '    lines.push("", "## All entries", "");',
  '    for (const e of entries) {',
  '      lines.push("### " + e.date + " — " + e.title);',
  '      lines.push("*Category:* " + e.category + (e.project ? "  ·  *Project:* " + e.project : "") + (e.hours ? "  ·  *Hours:* " + e.hours : "") + (e.isHighlight ? "  ·  ⭐" : ""));',
  '      if (e.description) lines.push("", e.description);',
  '      lines.push("");',
  '    }',
  '    const blob = new Blob([lines.join("\\n")], { type: "text/markdown" });',
  '    const url = URL.createObjectURL(blob);',
  '    const a = document.createElement("a");',
  '    a.href = url; a.download = "iwp-report-" + from + "_" + to + ".md"; a.click();',
  '    URL.revokeObjectURL(url);',
  '  };',
  '',
  '  return (',
  '    <div className="space-y-5">',
  '      <div className="flex items-center justify-between flex-wrap gap-2">',
  '        <h1 className="text-2xl font-semibold">Annual Report</h1>',
  '        <div className="flex gap-2 flex-wrap">',
  '          <button onClick={exportPdf} disabled={!!busy} className="rounded-md border border-border px-3 py-2 text-sm">',
  '            {busy === "pdf" ? "Generating…" : "Export PDF"}',
  '          </button>',
  '          <button onClick={exportXlsx} disabled={!!busy} className="rounded-md border border-border px-3 py-2 text-sm">',
  '            {busy === "xlsx" ? "Generating…" : "Export Excel"}',
  '          </button>',
  '          <button onClick={exportMarkdown} className="rounded-md bg-accent text-white px-3 py-2 text-sm">Export Markdown</button>',
  '        </div>',
  '      </div>',
  '      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">',
  '        <label className="text-sm"><div className="text-muted mb-1">From</div>',
  '          <input type="date" value={from} onChange={(e) => setFrom(e.target.value)}',
  '            className="w-full rounded-md border border-border bg-panel px-3 py-2" /></label>',
  '        <label className="text-sm"><div className="text-muted mb-1">To</div>',
  '          <input type="date" value={to} onChange={(e) => setTo(e.target.value)}',
  '            className="w-full rounded-md border border-border bg-panel px-3 py-2" /></label>',
  '        <div className="flex items-end gap-2 flex-wrap">',
  '          <button onClick={() => { setFrom(thisYear + "-01-01"); setTo(thisYear + "-12-31"); }} className="rounded-md border border-border px-3 py-2 text-sm">This year</button>',
  '          <button onClick={() => { setFrom(thisYear + "-01-01"); setTo(thisYear + "-06-30"); }} className="rounded-md border border-border px-3 py-2 text-sm">H1</button>',
  '          <button onClick={() => { setFrom(thisYear + "-01-01"); setTo(thisYear + "-03-31"); }} className="rounded-md border border-border px-3 py-2 text-sm">Q1</button>',
  '        </div>',
  '      </div>',
  '      <div ref={reportRef} className="bg-panel border border-border rounded-lg p-5 space-y-6">',
  '        <div>',
  '          <h2 className="text-lg font-semibold">Summary</h2>',
  '          <div className="text-sm text-muted">{from} → {to}</div>',
  '          <div className="grid grid-cols-3 gap-3 mt-3">',
  '            <div className="rounded-lg border border-border p-3"><div className="text-xs text-muted">Entries</div><div className="text-xl font-semibold">{entries.length}</div></div>',
  '            <div className="rounded-lg border border-border p-3"><div className="text-xs text-muted">Hours</div><div className="text-xl font-semibold">{totalHours.toFixed(1)}</div></div>',
  '            <div className="rounded-lg border border-border p-3"><div className="text-xs text-muted">Highlights</div><div className="text-xl font-semibold">{highlights.length}</div></div>',
  '          </div>',
  '        </div>',
  '        {byCategory.length > 0 && <div><h2 className="text-lg font-semibold mb-2">Category breakdown</h2><CategoryPie data={byCategory} /></div>}',
  '        {byMonth.length > 0 && <div><h2 className="text-lg font-semibold mb-2">Monthly activity</h2><MonthlyBar data={byMonth} /></div>}',
  '        {highlights.length > 0 && (',
  '          <div>',
  '            <h2 className="text-lg font-semibold mb-2">⭐ Highlights</h2>',
  '            <ul className="space-y-2 text-sm">',
  '              {highlights.map((e) => (',
  '                <li key={e.id} className="border border-border rounded-md p-3">',
  '                  <div className="font-medium">{e.title}</div>',
  '                  <div className="text-xs text-muted mt-1">{e.date} · {e.category}{e.project ? " · " + e.project : ""}</div>',
  '                </li>',
  '              ))}',
  '            </ul>',
  '          </div>',
  '        )}',
  '        <div>',
  '          <h2 className="text-lg font-semibold mb-2">By Category</h2>',
  '          {byCategory.map((c) => (',
  '            <details key={c.name} className="border border-border rounded-md mb-2">',
  '              <summary className="cursor-pointer px-3 py-2 text-sm"><b>{c.name}</b> — {c.count} entries, {c.hours.toFixed(1)}h</summary>',
  '              <ul className="px-5 pb-3 text-sm space-y-1">',
  '                {c.items.map((e) => <li key={e.id}>· {e.date} — {e.title}</li>)}',
  '              </ul>',
  '            </details>',
  '          ))}',
  '        </div>',
  '        <div>',
  '          <h2 className="text-lg font-semibold mb-2">By Project</h2>',
  '          {byProject.map((p) => (',
  '            <details key={p.name} className="border border-border rounded-md mb-2">',
  '              <summary className="cursor-pointer px-3 py-2 text-sm"><b>{p.name}</b> — {p.count} entries, {p.hours.toFixed(1)}h</summary>',
  '              <ul className="px-5 pb-3 text-sm space-y-1">',
  '                {p.items.map((e) => <li key={e.id}>· {e.date} — {e.title}</li>)}',
  '              </ul>',
  '            </details>',
  '          ))}',
  '        </div>',
  '      </div>',
  '    </div>',
  '  );',
  '}',
  ''
));

file('src/pages/Settings.jsx', S(
  "import { useEffect, useState } from 'react';",
  "import { useApi } from '../api/client.js';",
  "import { useTheme } from '../context/ThemeContext.jsx';",
  '',
  'export default function Settings() {',
  '  const api = useApi();',
  '  const { theme, toggle } = useTheme();',
  '  const [categories, setCategories] = useState([]);',
  '  const [newCat, setNewCat] = useState("");',
  '  const [importJson, setImportJson] = useState("");',
  '  const [importCsv, setImportCsv] = useState("");',
  '  const [msg, setMsg] = useState("");',
  '',
  '  const load = () => api.listCategories().then(setCategories).catch(() => {});',
  '  useEffect(() => { load(); }, []);',
  '',
  '  const addCat = async () => {',
  '    if (!newCat.trim()) return;',
  '    await api.createCategory({ name: newCat.trim() });',
  '    setNewCat(""); load();',
  '  };',
  '  const delCat = async (id) => { if (confirm("Delete category?")) { await api.deleteCategory(id); load(); } };',
  '',
  '  const doBackup = async () => {',
  '    const data = await api.call ? null : null;',
  '    // fetch raw backup',
  '    const pw = localStorage.getItem("iwp.password") || "";',
  '    const r = await fetch("/api?action=data.backup", { headers: { "x-app-password": pw } });',
  '    const blob = await r.blob();',
  '    const url = URL.createObjectURL(blob);',
  '    const a = document.createElement("a"); a.href = url; a.download = "iwp-backup-" + Date.now() + ".json"; a.click();',
  '    URL.revokeObjectURL(url);',
  '  };',
  '',
  '  const doRestore = async () => {',
  '    try {',
  '      const data = JSON.parse(importJson);',
  '      const res = await api.restore({ ...data, mode: "merge" });',
  '      setMsg("Restored. Total entries: " + res.entries);',
  '      setImportJson("");',
  '    } catch (e) { setMsg("Error: " + e.message); }',
  '  };',
  '',
  '  const doCsv = async () => {',
  '    try {',
  '      const res = await api.importCsv(importCsv);',
  '      setMsg("Imported " + res.inserted + " entries.");',
  '      setImportCsv("");',
  '    } catch (e) { setMsg("Error: " + e.message); }',
  '  };',
  '',
  '  return (',
  '    <div className="space-y-6">',
  '      <h1 className="text-2xl font-semibold">Settings</h1>',
  '      <section className="rounded-lg border border-border bg-panel p-4">',
  '        <h2 className="font-medium mb-2">Appearance</h2>',
  '        <button onClick={toggle} className="rounded-md border border-border px-3 py-2 text-sm">',
  '          {theme === "dark" ? "☀️  Switch to light" : "🌙  Switch to dark"}',
  '        </button>',
  '      </section>',
  '      <section className="rounded-lg border border-border bg-panel p-4">',
  '        <h2 className="font-medium mb-2">Categories</h2>',
  '        <div className="flex gap-2 mb-3">',
  '          <input value={newCat} onChange={(e) => setNewCat(e.target.value)} placeholder="New category name"',
  '            className="flex-1 rounded-md border border-border bg-bg px-3 py-2 text-sm" />',
  '          <button onClick={addCat} className="rounded-md border border-border px-3 py-2 text-sm">Add</button>',
  '        </div>',
  '        <ul className="space-y-1 text-sm">',
  '          {categories.map((c) => (',
  '            <li key={c.id} className="flex items-center justify-between border border-border rounded-md px-3 py-2">',
  '              <span>{c.name}</span>',
  '              <button onClick={() => delCat(c.id)} className="text-muted hover:text-red-500">Delete</button>',
  '            </li>',
  '          ))}',
  '        </ul>',
  '      </section>',
  '      <section className="rounded-lg border border-border bg-panel p-4 space-y-3">',
  '        <h2 className="font-medium">Data</h2>',
  '        <button onClick={doBackup} className="rounded-md border border-border px-3 py-2 text-sm">Download JSON backup</button>',
  '        <details>',
  '          <summary className="cursor-pointer text-sm">Restore from JSON</summary>',
  '          <textarea rows={5} value={importJson} onChange={(e) => setImportJson(e.target.value)}',
  '            placeholder="Paste backup JSON here"',
  '            className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2 text-xs font-mono" />',
  '          <button onClick={doRestore} className="mt-2 rounded-md bg-accent text-white px-3 py-2 text-sm">Restore (merge)</button>',
  '        </details>',
  '        <details>',
  '          <summary className="cursor-pointer text-sm">Import from CSV</summary>',
  '          <div className="text-xs text-muted mt-1">Header: <code>date,title,description,category,project,hours,status,isHighlight,links</code></div>',
  '          <textarea rows={5} value={importCsv} onChange={(e) => setImportCsv(e.target.value)}',
  '            placeholder="date,title,..."',
  '            className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2 text-xs font-mono" />',
  '          <button onClick={doCsv} className="mt-2 rounded-md bg-accent text-white px-3 py-2 text-sm">Import CSV</button>',
  '        </details>',
  '      </section>',
  '      {msg && <div className="text-sm text-muted">{msg}</div>}',
  '    </div>',
  '  );',
  '}',
  ''
));

// ═════════════════════════════════════════════════════════════
// README
// ═════════════════════════════════════════════════════════════

const B = String.fromCharCode(96);
const B3 = B + B + B;

file('README.md', S(
  '# IWP Work Tracker (v2)',
  '',
  'Personal productivity journal. Single-file backend, no serverless catch-all routing tricks.',
  '',
  '## Stack',
  '- React + Vite + Tailwind',
  '- ONE serverless function: `api/index.js` (Vercel auto-routes `/api/*` here)',
  '- Supabase (Postgres)',
  '- Recharts, jsPDF, xlsx',
  '',
  '## Setup',
  '',
  '1. **Supabase** → create project → SQL Editor → run `supabase/schema.sql`.',
  '2. **Supabase → Settings → API** → copy Project URL and service_role key.',
  '3. Create `.env` from `.env.example`:',
  '',
  B3,
  'SUPABASE_URL=https://xxxxx.supabase.co',
  'SUPABASE_SERVICE_ROLE_KEY=eyJ...',
  'APP_PASSWORD=yourpassword',
  B3,
  '',
  '4. Install and run:',
  '',
  B3,
  'npm install',
  'npm i -g vercel',
  'vercel dev',
  B3,
  '',
  '5. Open http://localhost:3000',
  '',
  '## Deploy',
  '',
  'Push to GitHub, import in Vercel, add the same 3 env vars, deploy.',
  '',
  '## API',
  '',
  'All endpoints are `/api?action=NAME&...params`.',
  'Every request needs header `x-app-password: <APP_PASSWORD>`.',
  '',
  'Actions: `ping`, `debug`, `entries.list`, `entries.create`, `entries.get`, `entries.update`,',
  '`entries.delete`, `entries.star`, `entries.duplicate`, `draft.get`, `draft.save`, `draft.clear`,',
  '`categories.list`, `categories.create`, `categories.update`, `categories.delete`,',
  '`projects.list`, `projects.names`, `stats.recent`, `stats.summary`, `data.backup`, `data.restore`,',
  '`data.import-csv`.',
  ''
));

// ═════════════════════════════════════════════════════════════
// WRITE
// ═════════════════════════════════════════════════════════════

let count = 0;
for (const [p, c] of Object.entries(files)) {
  const full = join(ROOT, p);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, c, 'utf8');
  count++;
}
mkdirSync(join(ROOT, 'public'), { recursive: true });
writeFileSync(join(ROOT, 'public', '.gitkeep'), '');

console.log('');
console.log('✅ Created ' + count + ' files in ' + ROOT);
console.log('');
console.log('Next steps:');
console.log('  1. Load supabase/schema.sql in your Supabase SQL Editor');
console.log('  2. cp .env.example .env    (fill in Supabase URL + service_role key + APP_PASSWORD)');
console.log('  3. npm install');
console.log('  4. npm i -g vercel');
console.log('  5. vercel dev');
console.log('  6. Open http://localhost:3000');
console.log('');